name: discord message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: webhook-notifications
        id: webhook-notifications
        uses: aledamen/webhook-notifications@v0.42
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-color: "#3278BD"
          message-icon: ${{ github.event.organization.avatar_url }}
          message-username: ${{ format('{0} {1}', env.REPO_NAME, env.STAGE) }}
          message-title: ${{ format('{0} Deploy Succeded', env.STAGE) }}
          message-text: ${{ format('{0}{1}', env.SUCCESS_MESSAGE, env.COMMIT_MESSAGE) }}