name: discord message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Load environment variables
        run: |
          export $(cat .env)
      - name: webhook-notifications
        id: webhook-notifications
        uses: aledamen/webhook-notifications@v0.47
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-color: "#3278BD"
          message-icon: ${{ github.event.organization.avatar_url }}
          message-username: ${{ format('{0} {1}', env.REPO_NAME, env.STAGE) }}
          message-action-title : Actions URL
          message-action-name:
          message-body-title: ${{ format('{0} Deploy Succeded', env.STAGE) }}
          message-body-text: ${{ format('{0}', env.SUCCESS_MESSAGE) }}